In [125]:
import numpy.matlib
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6])

In [5]:
print a

[1 2 3 4 5 6]


In [6]:
b = np.array([[1,2,3],[4,5,6]])

In [7]:
print b

[[1 2 3]
 [4 5 6]]


In [8]:
c = np.array([7,8,9],dtype=complex)

In [9]:
print c

[7.+0.j 8.+0.j 9.+0.j]


In [10]:
b.shape

(2, 3)

In [11]:
b.shape =(3,2)

In [12]:
print b

[[1 2]
 [3 4]
 [5 6]]


In [13]:
print a

[1 2 3 4 5 6]


In [14]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
d = np.arange(12)
print d

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
d.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [17]:
d.itemsize

8

In [18]:
d.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [19]:
empty_array = np.empty([3,3],dtype=int)

In [20]:
print empty_array

[[              0 139821124635024 139821131868944]
 [       31252808        31252808 139821134038288]
 [139821167317960 139821063452752 139821063452816]]


In [21]:
zero_array = np.zeros([2,3], dtype=float)

In [22]:
print zero_array

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
ones_array = np.ones([3,3],dtype=complex)

In [24]:
print ones_array

[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


In [25]:
f = [1,24,5,3,53,4]

In [26]:
print np.asarray(f,dtype=float)

[ 1. 24.  5.  3. 53.  4.]


In [27]:
data = [(1,1),(2,2),(3,3)]

In [28]:
print np.asarray(data)

[[1 1]
 [2 2]
 [3 3]]


In [29]:
str = "This is a string"

In [30]:
print np.frombuffer(str,dtype="S1")

['T' 'h' 'i' 's' ' ' 'i' 's' ' ' 'a' ' ' 's' 't' 'r' 'i' 'n' 'g']


In [31]:
lst  = range(10)

In [32]:
items = iter(lst)

In [52]:
print np.fromiter(items,dtype=float)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [39]:
data = np.arange(50,71,4)

In [40]:
print data

[50 54 58 62 66 70]


In [46]:
nums = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])

In [47]:
print nums

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
print nums[0:,2] , nums[1:,1]

[ 3  7 11] [ 6 10]


In [57]:
ser1 = np.linspace(1,10,5)

In [58]:
print ser1

[ 1.    3.25  5.5   7.75 10.  ]


In [62]:
print nums.min() , nums.max() , nums.sum()

1 12 78


In [64]:
print nums.sum(axis=0) , nums.sum(axis=1)

[15 18 21 24] [10 26 42]


In [67]:
print nums 
print np.sqrt(nums)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]


In [68]:
print np.std(nums)

3.452052529534663


In [69]:
nums2 = nums
print nums2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [73]:
res =  nums + nums2
print res

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [74]:
print res - nums

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [76]:
print nums*nums2

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [79]:
print res/nums

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [82]:
print nums

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [83]:
print res

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [86]:
print np.vstack((nums,res))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [87]:
print np.hstack((nums,res))

[[ 1  2  3  4  2  4  6  8]
 [ 5  6  7  8 10 12 14 16]
 [ 9 10 11 12 18 20 22 24]]


In [88]:
print np.ravel(nums)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [89]:
#Numpy Special Functions 
# e ~ 2.7
print np.exp(nums)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]
 [8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05]]


In [90]:
print np.log(nums)

[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]]


In [91]:
print np.log10(nums)

[[0.         0.30103    0.47712125 0.60205999]
 [0.69897    0.77815125 0.84509804 0.90308999]
 [0.95424251 1.         1.04139269 1.07918125]]


In [95]:
#String Functions
s1 = np.char.add(["Hello "] , ["Jupyter"])
print s1

['Hello Jupyter']


In [96]:
s2 = np.char.add(["Jupyter " , "Machine "],["Lab" , "Learning"])
print s2

['Jupyter Lab' 'Machine Learning']


In [98]:
print np.char.multiply("Entertainment ",3)

Entertainment Entertainment Entertainment 


In [99]:
print np.char.center("Applied Informatics",100,fillchar="-")

----------------------------------------Applied Informatics-----------------------------------------


In [100]:
print np.char.splitlines("Artificial Intelligence\nData Science\rMachine Learning")

['Artificial Intelligence', 'Data Science', 'Machine Learning']


In [102]:
print np.char.capitalize("hello jupyter labs")

Hello jupyter labs


In [104]:
print np.char.title("hello jupyter labs")

Hello Jupyter Labs


In [109]:
a = np.char.encode("data","cp500")
print a

����


In [110]:
print np.char.decode(a,"cp500")

data


In [113]:
type = np.dtype([("name","S50")])
names = np.array(["Owais Mushtaq","Muneer Ashraf","Faizan Naseer","Faizaan Yousuf","Nadeem Nazeer","Shahid Ashraf","Saahyl Sheikh"],dtype=type)
print names

[('Owais Mushtaq',) ('Muneer Ashraf',) ('Faizan Naseer',)
 ('Faizaan Yousuf',) ('Nadeem Nazeer',) ('Shahid Ashraf',)
 ('Saahyl Sheikh',)]


In [114]:
print np.sort(names,order="name")

[('Faizaan Yousuf',) ('Faizan Naseer',) ('Muneer Ashraf',)
 ('Nadeem Nazeer',) ('Owais Mushtaq',) ('Saahyl Sheikh',)
 ('Shahid Ashraf',)]


In [115]:
print nums

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [118]:
y = np.where(nums > 5)
print y

(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))


In [119]:
print nums[y]

[ 6  7  8  9 10 11 12]


In [122]:
condition = np.mod(nums,2) != 0
print np.extract(condition,nums)

[ 1  3  5  7  9 11]


In [129]:
print np.matlib.ones([2,3],dtype=int)

[[1 1 1]
 [1 1 1]]


In [130]:
print np.matlib.eye(n=3,M=4,k=1,dtype=int)

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [136]:
print np.matlib.identity(4,dtype=int)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [138]:
print np.matrix("1,2,3;4,5,6;7,8,9")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
